# COMBINED MODEL DEVELOPEMENT

#### Here I am going to create combined model which is consists of seven classifiers 

I have processed and cleaned amazon review data in other notebook which is also uploded as Final<br>
Here I have just compared different model for binary classification 

In [4]:
import numpy as np
import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score 
from statistics import mode
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix 

In [5]:
data=pd.read_csv("binaryrating.csv")

In [147]:
print(data.shape)
data.head()

(40000, 2)


review binary_rating
0  found game bit complicated expected played two...           low
1  im sure would love game could play loved hitma...           low
2  like bf game work wireless xbox controller don...          high
3  game requires open online account play game co...           low
4  st shipment received book instead gamend shipm...           low

In [8]:
tfidf = TfidfVectorizer(max_features=20000)
word_matrix=tfidf.fit_transform(data['review'].values.astype('U'))
print(word_matrix.shape)

(40000, 20000)


In [9]:
train_x,test_x,train_y,test_y=train_test_split(word_matrix,data['binary_rating'],test_size=0.05, random_state=42)

In [34]:
from sklearn.naive_bayes import MultinomialNB
from sklearn.linear_model import LogisticRegression, SGDClassifier
from sklearn.svm import LinearSVC
from sklearn.ensemble import RandomForestClassifier
from xgboost import XGBClassifier
from sklearn.neighbors import KNeighborsClassifier

In [18]:
lr=LogisticRegression()
lr.fit(train_x,train_y)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [53]:
test_pred=lr.predict(test_x)

print(accuracy_score(test_y,test_pred),'\n')
print(confusion_matrix(test_y,test_pred),'\n')
print(classification_report(test_y,test_pred))

0.8305 

[[823 185]
 [154 838]] 

              precision    recall  f1-score   support

        high       0.84      0.82      0.83      1008
         low       0.82      0.84      0.83       992

    accuracy                           0.83      2000
   macro avg       0.83      0.83      0.83      2000
weighted avg       0.83      0.83      0.83      2000



In [51]:
knn=KNeighborsClassifier(n_neighbors=25)
knn.fit(train_x,train_y)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=25, p=2,
                     weights='uniform')

In [52]:
knn_pred=knn.predict(test_x)

print(accuracy_score(test_y,knn_pred),'\n')
print(confusion_matrix(test_y,knn_pred),'\n')
print(classification_report(test_y,knn_pred))

0.716 

[[831 177]
 [391 601]] 

              precision    recall  f1-score   support

        high       0.68      0.82      0.75      1008
         low       0.77      0.61      0.68       992

    accuracy                           0.72      2000
   macro avg       0.73      0.72      0.71      2000
weighted avg       0.73      0.72      0.71      2000



In [27]:
sgd=SGDClassifier()
sgd.fit(train_x,train_y)

SGDClassifier(alpha=0.0001, average=False, class_weight=None,
              early_stopping=False, epsilon=0.1, eta0=0.0, fit_intercept=True,
              l1_ratio=0.15, learning_rate='optimal', loss='hinge',
              max_iter=1000, n_iter_no_change=5, n_jobs=None, penalty='l2',
              power_t=0.5, random_state=None, shuffle=True, tol=0.001,
              validation_fraction=0.1, verbose=0, warm_start=False)

In [42]:
sgd_pred=sgd.predict(test_x)

print(accuracy_score(test_y,sgd_pred),'\n')
print(confusion_matrix(test_y,sgd_pred),'\n')
print(classification_report(test_y,sgd_pred))

0.831 

[[827 181]
 [157 835]] 

              precision    recall  f1-score   support

        high       0.84      0.82      0.83      1008
         low       0.82      0.84      0.83       992

    accuracy                           0.83      2000
   macro avg       0.83      0.83      0.83      2000
weighted avg       0.83      0.83      0.83      2000



In [29]:
NB=MultinomialNB()
NB.fit(train_x,train_y)

MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [30]:
NB_pred=NB.predict(test_x)

print(accuracy_score(test_y,NB_pred),'\n')
print(confusion_matrix(test_y,NB_pred),'\n')
print(classification_report(test_y,NB_pred))

0.8085 

[[792 216]
 [167 825]] 

              precision    recall  f1-score   support

        high       0.83      0.79      0.81      1008
         low       0.79      0.83      0.81       992

    accuracy                           0.81      2000
   macro avg       0.81      0.81      0.81      2000
weighted avg       0.81      0.81      0.81      2000



In [16]:
svc=LinearSVC()
svc.fit(train_x,train_y)

LinearSVC(C=1.0, class_weight=None, dual=True, fit_intercept=True,
          intercept_scaling=1, loss='squared_hinge', max_iter=1000,
          multi_class='ovr', penalty='l2', random_state=None, tol=0.0001,
          verbose=0)

In [17]:
svc_pred=svc.predict(test_x)

print(accuracy_score(test_y,svc_pred),'\n')
print(confusion_matrix(test_y,svc_pred),'\n')
print(classification_report(test_y,svc_pred))

0.82 

[[823 185]
 [175 817]] 

              precision    recall  f1-score   support

        high       0.82      0.82      0.82      1008
         low       0.82      0.82      0.82       992

    accuracy                           0.82      2000
   macro avg       0.82      0.82      0.82      2000
weighted avg       0.82      0.82      0.82      2000



In [23]:
xgb=XGBClassifier()
xgb.fit(train_x,train_y)

XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
              colsample_bynode=1, colsample_bytree=1, gamma=0,
              learning_rate=0.1, max_delta_step=0, max_depth=3,
              min_child_weight=1, missing=None, n_estimators=100, n_jobs=1,
              nthread=None, objective='binary:logistic', random_state=0,
              reg_alpha=0, reg_lambda=1, scale_pos_weight=1, seed=None,
              silent=None, subsample=1, verbosity=1)

In [24]:
xgb_pred=xgb.predict(test_x)

print(accuracy_score(test_y,xgb_pred),'\n')
print(confusion_matrix(test_y,xgb_pred),'\n')
print(classification_report(test_y,xgb_pred))

0.764 

[[718 290]
 [182 810]] 

              precision    recall  f1-score   support

        high       0.80      0.71      0.75      1008
         low       0.74      0.82      0.77       992

    accuracy                           0.76      2000
   macro avg       0.77      0.76      0.76      2000
weighted avg       0.77      0.76      0.76      2000



In [25]:
rf=RandomForestClassifier()
rf.fit(train_x,train_y)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=100,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

In [26]:
rf_pred=rf.predict(test_x)

print(accuracy_score(test_y,rf_pred),'\n')
print(confusion_matrix(test_y,rf_pred),'\n')
print(classification_report(test_y,rf_pred))

0.824 

[[793 215]
 [137 855]] 

              precision    recall  f1-score   support

        high       0.85      0.79      0.82      1008
         low       0.80      0.86      0.83       992

    accuracy                           0.82      2000
   macro avg       0.83      0.82      0.82      2000
weighted avg       0.83      0.82      0.82      2000



<b>Let's save our models as elements of list in pickle file</b>

In [55]:
import pickle
#model=[lr,knn,sgd,NB,svc,xgb,rf]
#f = open("binaryreview_classification.pkl", "wb")
#pickle.dump(model,f)
#f.close()

In [56]:
f = open("binaryreview_classification.pkl","rb")
a=pickle.load(f)
print(a[1])

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=25, p=2,
                     weights='uniform')


In [125]:
def classify(data):
    predicted=[]
    confidence=[]
    
    for model in a:
        pred=model.predict(data)
        pred_list=pred.tolist()
            
        if(len(predicted)==0):
            predicted=predicted+pred_list
        else:
            for i in range(0,len(pred_list)):
                predicted[i]=predicted[i] +"|"+ pred_list[i]
                
    for i in range(0,len(predicted)):
        predicted[i]=predicted[i].split('|')
        confidence.append((predicted[i].count(mode(predicted[i]))/len(predicted[i]))*100)
        predicted[i]=mode(predicted[i])
            
    return predicted,confidence       

Above function will return prediction with confidence<br>
I have used voting system means whichever label has more vote will be shown as output  

In [126]:
combine_pred,confidence=classify(test_x)

In [145]:
print("prediction:{0} with confidence:{1} and actual:{2}".format(combine_pred[656],confidence[656],test_y.iloc[656]))

prediction:low with confidence:85.71428571428571 and actual:low


In [146]:
print(accuracy_score(test_y,combine_pred),'\n')
print(confusion_matrix(test_y,combine_pred),'\n')
print(classification_report(test_y,combine_pred))

0.836 

[[830 178]
 [150 842]] 

              precision    recall  f1-score   support

        high       0.85      0.82      0.84      1008
         low       0.83      0.85      0.84       992

    accuracy                           0.84      2000
   macro avg       0.84      0.84      0.84      2000
weighted avg       0.84      0.84      0.84      2000



As you can see accuracy is nearly same as individual models but plus point is that now we can see confidence Hence we can be more sure

<b>Key Points: </b>

SGD , RF and XGB relatively takes more time in training then other algorithms
           
SVC kernel algorithm takes highest amount time since it has to do lot of computation, Here we have used SVC linear which is very fast to train

SVC linear and LR are basically same, only difference is there loss function

You can save multiple models in pickle file as lists